module.exports = {
    INTERNAL_SERVER_ERROR: "Internal Server Error",
    ERROR_LOGOUT: "Error in logout",
    LOGOUT_SUCCESS: "User logged out Successfully!",
    FIRM_NAME_NOT_FOUND: "Firm name not found.",
    MASTER_MAKER_NAME_NOT_FOUND: "Master maker name not found.",
    MASTER_MAKER_LOV_NOT_FOUND: "Master maker lov not found.",
    MATERIAL_NAME_NOT_FOUND: "Material name not found.",
    MATERIAL_TYPE_NOT_FOUND: "Material type not found.",
    MATERIAL_DESCRIPTION_NOT_FOUND: "Material description not found.",
    MATERIAL_HSN_CODE_NOT_FOUND: "Material hsn code not found.",
    MATERIAL_UOM_NOT_FOUND: "Material uom not found.",
    IS_SERIAL_NUMBER_NOT_FOUND: "Is Serial Number not found.",
    MATERIAL_ALREADY_EXIST: "Material already exists.",
    SERIAL_NUMBER_NOT_FOUND: "Serial number not found.",
    NAME_LENGTH: "Please check the material name length.",
    FIRM_NAME_LENGTH: "Please check the firm name length.",
    MASTER_MAKER_NAME_LENGTH: "Please check the master maker name length.",
    MASTER_MAKER_LOV_LENGTH: "Please check the master maker lov length.",
    MASTER_MAKER_CODE_NOT_FOUND: "Master maker code not found.",
    MASTER_MAKER_ID_NOT_FOUND: "Master maker id not found.",
    GST_NUMBER_REQUIRED: "GST number required.",
    MOBILE_NUMBER_REQUIRED: "Mobile number required.",
    ADDRESS_REQUIRED: "Address required.",
    PINCODE_REQUIRED: "Pincode required",
    REGISTERED_OFFICE_ADDRESS_REQUIRED: "Registered office address required.",
    REGISTERED_OFFICE_PINCODE_REQUIRED: "Registered office pincode required",
    CURRENT_OFFICE_ADDRESS_REQUIRED: "Current office address required.",
    CURRENT_OFFICE_PINCODE_REQUIRED: "Current office pincode required",
    FIRM_ALREADY_EXIST: "Firm already exists.",
    CREATE_FIRM_FAILURE: "Failed to create firm.",
    CREATE_MASTER_MAKER_FAILURE: "Failed to create master maker.",
    CREATE_MASTER_MAKER_LOV_FAILURE: "Failed to create master maker lov.",
    CREATE_MATERIAL_FAILURE: "Failed to create material.",
    FETCH_FIRM_FAILURE: "Failed to fetch firm.",
    FETCH_MASTER_MAKER_FAILURE: "Failed to fetch master maker.",
    FETCH_MASTER_MAKER_LOV_FAILURE: "Failed to fetch master maker lov.",
    FETCH_MATERIAL_FAILURE: "Failed to fetch material.",
    MISSING_FIRM_DETAILS: "Missing firm details.",
    MISSING_MATERIAL_DETAILS: "Missing material details.",
    FIRM_ID_REQUIRED: "Firm id required.",
    MASTER_MAKER_ID_REQUIRED: "Master maker id required.",
    MASTER_MAKER_LOV_ID_REQUIRED: "Master maker lov id required.",
    MATERIAL_ID_REQUIRED: "Material id required.",
    FETCH_FIRM_LIST_FAILURE: "Failed to fetch firm list.",
    FETCH_MASTER_MAKER_LIST_FAILURE: "Failed to fetch master maker list.",
    FETCH_MASTER_MAKER_LOV_LIST_FAILURE: "Failed to fetch master maker lov list.",
    FETCH_MATERIAL_LIST_FAILURE: "Failed to fetch material list.",
    DELETE_FIRM_FAILURE: "Failed to delete firm.",
    DELETE_MASTER_MAKER_FAILURE: "Failed to delete master maker.",
    DELETE_MASTER_MAKER_LOV_FAILURE: "Failed to delete master maker lov.",
    DELETE_MATERIAL_FAILURE: "Failed to delete material.",
    MISSING_MASTER_MAKER_DETAILS: "Missing master maker details.",
    MISSING_MASTER_MAKER_LOV_DETAILS: "Missing master maker lov details.",
    MASTER_MAKER_ALREADY_EXIST: "Master maker already exists.",
    MASTER_MAKER_LOV_ALREADY_EXIST: "Master maker lov already exists.",
    MASTER_NAME_REQUIRED: "Master name required.",
    FETCH_LOV_FAILURE: "Failed to fetch lov.",
    FIRM_NOT_EXIST: "Firm not exists.",
    MASTER_MAKER_NOT_EXIST: "Master maker not exists.",
    MASTER_MAKER_LOV_NOT_EXIST: "Master maker lov not exists.",
    MATERIAL_NOT_EXIST: "Material not exists.",
    FIRM_UPDATE_FAILURE: "Failed to update firm.",
    MASTER_MAKER_UPDATE_FAILURE: "Failed to update master maker.",
    MASTER_MAKER_LOV_UPDATE_FAILURE: "Failed to update master maker lov.",
    MATERIAL_UPDATE_FAILURE: "Failed to update material",
    INVALID_EMAIL_OR_PASSWORD: "Incorrect email or password",
    EMAIL_PASSWORD_NOT_FOUND: "Invalid username or password.",
    USER_NOT_FOUND: "User not found.",
    USER_NOT_ACTIVE: "User is not activated.",
    USER_EXIST: "User already exists.",
    USER_REGISTERED: "User registered successfully.",
    TOKEN_EXPIRED: "Token Expired",
    FORMAT_AUTHORIZATION_BEARER: "Format is authorization.",
    NO_AUTHORIZATION_HEADER: "Auth token not found in the request. Log in to authenticate.",
    INVALID_PASSWORD: "Invalid password.",
    SESSION_EXPIRED: "Your session has expired. Please login again.",
    INVALID_PASSWORD_ITERATION: "Login failed",
    EMAIL_NOT_FOUND: "Email not found.",
    INVALID_EMAIL: "Please provide a valid email.",
    INVALID_BOOLEAN: "Please provide a valid boolean.",
    INVALID_FLOAT: "Please provide a valid float number.",
    INVALID_INTEGER: "Please provide a valid integer.",
    PASSWORD_NOT_FOUND: "Password not found.",
    FIRST_NAME_NOT_FOUND: "First name not found.",
    PLEASE_CHECK_FIRST_NAME_LENGTH: "Please check first name length.",
    LAST_NAME_NOT_FOUND: "Last name not found.",
    PLEASE_CHECK_LAST_NAME_LENGTH: "Please check last name length.",
    SUPPLIER_NAME_NOT_FOUND: "Supplier name not found.",
    SUPPLIER_NAME_LENGTH: "Please check the Supplier name length.",
    SUPPLIER_ALREADY_EXIST: "SUPPLIER already exists.",
    CREATE_SUPPLIER_FAILURE: "Failed to create SUPPLIER.",
    FETCH_SUPPLIER_FAILURE: "Failed to fetch SUPPLIER.",
    MISSING_SUPPLIER_DETAILS: "Missing SUPPLIER details.",
    SUPPLIER_ID_REQUIRED: "SUPPLIER id required.",
    FETCH_SUPPLIER_LIST_FAILURE: "Failed to fetch SUPPLIER list.",
    DELETE_SUPPLIER_FAILURE: "Failed to delete SUPPLIER.",
    SUPPLIER_NOT_EXIST: "SUPPLIER not exists.",
    SUPPLIER_UPDATE_FAILURE: "Failed to update SUPPLIER.",
    PROJECT_SITE_STORE_NAME_NOT_FOUND: "Project-site-store name not found.",
    SUPPLIER_REPAIR_CENTER_NAME_NOT_FOUND: "Supplier repair center name not found.",
    PROJECT_SITE_STORE_NAME_LENGTH: "Please check the Project-site-store name length.",
    SUPPLIER_REPAIR_CENTER_NAME_LENGTH: "Please check the supplier repair center name length.",
    PROJECT_SITE_STORE_ALREADY_EXIST: "Project-site-store already exists.",
    SUPPLIER_REPAIR_CENTER_ALREADY_EXIST: "Supplier repair center already exists.",
    CREATE_PROJECT_SITE_STORE_FAILURE: "Failed to create Project-site-store.",
    CREATE_SUPPLIER_REPAIR_CENTER_FAILURE: "Failed to create Supplier repair center.",
    FETCH_PROJECT_SITE_STORE_FAILURE: "Failed to fetch Project-site-store.",
    FETCH_SUPPLIER_REPAIR_CENTER_FAILURE: "Failed to fetch Supplier repair center.",
    MISSING_PROJECT_SITE_STORE_DETAILS: "Missing Project-site-store details.",
    MISSING_SUPPLIER_REPAIR_CENTER_DETAILS: "Missing Project-site-store details.",
    PROJECT_SITE_STORE_ID_REQUIRED: "Project-site-store id required.",
    SUPPLIER_REPAIR_CENTER_ID_REQUIRED: "Supplier repair center id required.",
    FETCH_PROJECT_SITE_STORE_LIST_FAILURE: "Failed to fetch Project-site-store list.",
    DELETE_PROJECT_SITE_STORE_FAILURE: "Failed to delete Project-site-store.",
    DELETE_SUPPLIER_REPAIR_CENTER_FAILURE: "Failed to delete Supplier repair center.",
    PROJECT_SITE_STORE_NOT_EXIST: "Project-site-store not exists.",
    SUPPLIER_REPAIR_CENTER_NOT_EXIST: "Supplier repair center not exists.",
    PROJECT_SITE_STORE_UPDATE_FAILURE: "Failed to update Project-site-store.",
    SUPPLIER_REPAIR_CENTER_UPDATE_FAILURE: "Failed to update Supplier repair center.",
    LOCATION_SITE_STORE_NAME_NOT_FOUND: "Location-site-store name not found.",
    USER_ID_NOT_FOUND: "User id not found.",
    LOCATION_SITE_STORE_NAME_LENGTH: "Please check the Location-site-store name length.",
    LOCATION_SITE_STORE_ALREADY_EXIST: "Location-site-store already exists.",
    SUPERVISOR_ASSIGNMENTS_ALREADY_EXIST: "Supervisor assignments already exists.",
    CREATE_LOCATION_SITE_STORE_FAILURE: "Failed to create Location-site-store.",
    CREATE_SUPERVISOR_ASSIGNMENTS_FAILURE: "Failed to create Supervisor-assignments.",
    FETCH_LOCATION_SITE_STORE_FAILURE: "Failed to fetch Location-site-store.",
    FETCH_SUPERVISOR_ASSIGNMENTS_FAILURE: "Failed to fetch Supervisor assignments.",
    MISSING_LOCATION_SITE_STORE_DETAILS: "Missing Location-site-store details.",
    SUPERVISOR_ASSIGNMENTS_DETAILS: "Missing supervisor assignments details.",
    LOCATION_SITE_STORE_ID_REQUIRED: "Location-site-store id required.",
    SUPERVISOR_ASSIGNMENTS_ID_REQUIRED: "Supervisor assignments id required.",
    FETCH_LOCATION_SITE_STORE_LIST_FAILURE: "Failed to fetch Location-site-store list.",
    FETCH_SUPERVISOR_ASSIGNMENTS_LIST_FAILURE: "Failed to fetch supervisor assignments list.",
    DELETE_LOCATION_SITE_STORE_FAILURE: "Failed to delete Location-site-store.",
    DELETE_SUPERVISOR_ASSIGNMENTS_FAILURE: "Failed to delete supervisor assignments.",
    LOCATION_SITE_STORE_NOT_EXIST: "Location-site-store not exists.",
    SUPERVISOR_ASSIGNMENTS_NOT_EXIST: "Supervisor assignments not exists.",
    LOCATION_SITE_STORE_UPDATE_FAILURE: "Failed to update Location-site-store.",
    SUPERVISOR_ASSIGNMENTS_UPDATE_FAILURE: "Failed to update supervisor assignments.",
    CONTRACTOR_STORE_NAME_NOT_FOUND: "Contractor-store name not found.",
    CONTRACTOR_STORE_NAME_LENGTH: "Please check the Contractor-store name length.",
    CONTRACTOR_STORE_ALREADY_EXIST: "Contractor-store already exists.",
    CREATE_CONTRACTOR_STORE_FAILURE: "Failed to create Contractor-store.",
    FETCH_CONTRACTOR_STORE_FAILURE: "Failed to fetch Contractor-store.",
    MISSING_CONTRACTOR_STORE_DETAILS: "Missing Contractor-store details.",
    CONTRACTOR_STORE_ID_REQUIRED: "Contractor-store id required.",
    FETCH_CONTRACTOR_STORE_LIST_FAILURE: "Failed to fetch Contractor-store list.",
    DELETE_CONTRACTOR_STORE_FAILURE: "Failed to delete Contractor-store.",
    CONTRACTOR_STORE_NOT_EXIST: "Contractor-store not exists.",
    CONTRACTOR_STORE_UPDATE_FAILURE: "Failed to update Contractor-store.",
    FIRM_LOCATION_ALREADY_EXIST: "Firm-location already exists.",
    CREATE_FIRM_LOCATION_FAILURE: "Failed to create Firm-location.",
    FETCH_FIRM_LOCATION_FAILURE: "Failed to fetch Firm-location.",
    MISSING_FIRM_LOCATION_DETAILS: "Missing Firm-location details.",
    FIRM_LOCATION_ID_REQUIRED: "Firm-location id required.",
    FETCH_FIRM_LOCATION_LIST_FAILURE: "Failed to fetch Firm-location list.",
    DELETE_FIRM_LOCATION_FAILURE: "Failed to delete Firm-location.",
    FIRM_LOCATION_NOT_EXIST: "Firm-location not exists.",
    FIRM_LOCATION_UPDATE_FAILURE: "Failed to update Firm-location.",
    MISSING_COMPANY_DETAILS: "Missing company details.",
    COMPANY_ALREADY_EXIST: "Company already exists.",
    FETCH_COMPANY_FAILURE: "Failed to fetch company.",
    CREATE_COMPANY_FAILURE: "Failed to create company.",
    COMPANY_NAME_NOT_FOUND: "Company name not found.",
    COMPANY_NAME_LENGTH: "Please check the company name length.",
    COMPANY_CODE_NOT_FOUND: "Company code not found.",
    COMPANY_ID_REQUIRED: "company id required.",
    COMPANY_NOT_EXIST: "COmpany not exists.",
    COMPANY_UPDATE_FAILURE: "Failed to update company.",
    FETCH_COMPANY_LIST_FAILURE: "Failed to fetch company list.",
    DELETE_COMPANY_FAILURE: "Failed to delete company.",
    COUNTRY_NAME_NOT_FOUND: "Country Name not found.",
    ALL_MASTERS_NAME_NOT_FOUND: "All masters Name not found.",
    ALL_MASTER_COLUMNS_NAME_NOT_FOUND: "All master columns Name not found.",
    COUNTRY_NAME_LENGTH: "Please check the Country name length.",
    ALL_MASTERS_NAME_LENGTH: "Please check the all masters name length.",
    ALL_MASTER_COLUMNS_NAME_LENGTH: "Please check the all master columns name length.",
    COUNTRY_ALREADY_EXIST: "Country already exists.",
    ALL_MASTERS_LIST_ALREADY_EXIST: "All masters list already exists.",
    ALL_MASTER_COLUMNS_LIST_ALREADY_EXIST: "All master columns list already exists.",
    COUNTRY_FAILURE: "Failed to fetch country.",
    COUNTRY_ID_REQUIRED: "Country id required.",
    ALL_MASTERS_LIST_ID_REQUIRED: "All masters list id required.",
    ALL_MASTER_COLUMN_LIST_ID_REQUIRED: "All master column list id required.",
    COUNTRY_UPDATE_FAILURE: "Failed to update country.",
    ALL_MASTERS_LIST_UPDATE_FAILURE: "Failed to update all masters list.",
    ALL_MASTER_COLUMNS_LIST_UPDATE_FAILURE: "Failed to update all master columns list.",
    MISSING_COUNTRY_DETAILS: "Missing country details.",
    MISSING_ALL_MASTERS_LIST_DETAILS: "Missing all masters list details.",
    MISSING_ALL_MASTER_COLUMNS_LIST_DETAILS: "Missing all master columns list details.",
    COUNTRY_NOT_EXIST: "Country not exists.",
    ALL_MASTERS_LIST_NOT_EXIST: "All masters list not exists.",
    ALL_MASTER_COLUMNS_LIST_NOT_EXIST: "All master columns list not exists.",
    CREATE_COUNTRY_FAILURE: "Failed to create country.",
    CREATE_ALL_MASTERS_LIST_FAILURE: "Failed to create all masters list.",
    CREATE_ALL_MASTER_COLUMNS_LIST_FAILURE: "Failed to create all master columns list.",
    FETCH_COUNTRY_LIST_FAILURE: "Failed to fetch firm list.",
    FETCH_ALL_MASTERS_LIST_FAILURE: "Failed to all masters list.",
    FETCH_ALL_MASTER_COLUMNS_LIST_FAILURE: "Failed to all master columns list.",
    MISSING_CUSTOMER_DETAILS: "Missing customers details",
    CUSTOMER_ALREADY_EXIST: "Customer already exists.",
    CUSTOMER_ID_REQUIRED: "Customer id required.",
    CUSTOMER_NOT_EXIST: "Customer not exists.",
    FETCH_CUSTOMER_FAILURE: "Failed to fetch Customer .",
    CREATE_CUSTOMER_FAILURE: "Failed to create Customer .",
    CUSTOMER_NAME_NOT_FOUND: "Customer name not found.",
    CUSTOMER_NAME_LENGTH: "Please check the Customer  name length.",
    CUSTOMER_CODE_NOT_FOUND: "Customer  code not found.",
    CUSTOMER_UPDATE_FAILURE: "Failed to update Customer.",
    FETCH_CUSTOMER_LIST_FAILURE: "Failed to fetch Customer list.",
    DELETE_CUSTOMER_FAILURE: "Failed to delete Customer .",
    MISSING_STATE_DETAILS: "Missing state details.",
    STATE_ALREADY_EXIST: "State  already exists.",
    STATE_NAME_NOT_FOUND: "State Name not found.",
    STATE_NAME_LENGTH: "Please check the State name length.",
    COUNTRY_CODE_NOT_FOUND: "Country code not found.",
    STATE_CODE_NOT_FOUND: "State code not found.",
    STATE_ID_REQUIRED: "State id required.",
    STATE_NOT_EXIST: "State not exists.",
    STATE_UPDATE_FAILURE: "Failed to update state.",
    STATE_FAILURE: "Failed to fetch state.",
    FETCH_STATE_LIST_FAILURE: "Failed to fetch state list.",
    DELETE_COUNTRY_FAILURE: "Failed to delete country.",
    DELETE_ALL_MASTERS_LIST_FAILURE: "Failed to delete all masters list.",
    DELETE_ALL_MASTER_COLUMNS_LIST_FAILURE: "Failed to delete all master columns list.",
    DELETE_STATE_FAILURE: "Failed to delete state.",
    MISSING_PROJECT_DETAILS: "Missing projects details",
    PROJECT_ALREADY_EXIST: "project already exists.",
    PROJECT_ID_REQUIRED: "project id required.",
    PROJECT_NOT_EXIST: "project not exists.",
    FETCH_PROJECT_FAILURE: "Failed to fetch project .",
    CREATE_PROJECT_FAILURE: "Failed to create project .",
    PROJECT_NAME_NOT_FOUND: "project name not found.",
    PROJECT_NAME_LENGTH: "Please check the project  name length.",
    PROJECT_CODE_NOT_FOUND: "project  code not found.",
    PROJECT_UPDATE_FAILURE: "Failed to update project.",
    FETCH_PROJECT_LIST_FAILURE: "Failed to fetch project list.",
    DELETE_PROJECT_FAILURE: "Failed to delete project .",
    MISSING_CITY_DETAILS: "Missing city details.",
    CITY_ALREADY_EXIST: "City already exists.",
    CITY_ID_REQUIRED: "City id required.",
    CITY_NOT_EXIST: "City not exists.",
    WORK_AREA_ASSIGNMENT_NOT_EXIST: "Work area assignment not exists.",
    CITY_UPDATE_FAILURE: "Failed to update city.",
    CITY_FAILURE: "Failed to fetch city.",
    FETCH_CITY_LIST_FAILURE: "Failed to fetch city list.",
    DELETE_CITY_FAILURE: "Failed to delete city.",
    CITY_NAME_NOT_FOUND: "City Name not found.",
    CITY_NAME_LENGTH: "Please check the City name length.",
    CITY_CODE_NOT_FOUND: "City code not found.",
    MISSING_CUSTOMER_DEPARTMENT_DETAILS: "Missing customer department details",
    CUSTOMER_DEPARTMENT_ALREADY_EXIST: "customer department already exists.",
    CUSTOMER_DEPARTMENT_ID_REQUIRED: "customer department id required.",
    CUSTOMER_DEPARTMENT_NOT_EXIST: "customer department not exists.",
    FETCH_CUSTOMER_DEPARTMENT_FAILURE: "Failed to fetch customer department .",
    CREATE_CUSTOMER_DEPARTMENT_FAILURE: "Failed to create customer department .",
    CUSTOMER_DEPARTMENT_NAME_NOT_FOUND: "customer department name not found.",
    CUSTOMER_DEPARTMENT_NAME_LENGTH: "Please check the customer department name length.",
    CUSTOMER_DEPARTMENT_CODE_NOT_FOUND: "customer department code not found.",
    CUSTOMER_DEPARTMENT_UPDATE_FAILURE: "Failed to update customer department",
    FETCH_CUSTOMER_DEPARTMENT_LIST_FAILURE: "Failed to fetch customer department list.",
    DELETE_CUSTOMER_DEPARTMENT_FAILURE: "Failed to delete customer department .",
    CUSTOMER_STORE_NAME_NOT_FOUND: "Customer-store name not found.",
    CUSTOMER_STORE_NAME_LENGTH: "Please check the Customer-store name length.",
    CUSTOMER_STORE_ALREADY_EXIST: "Customer-store already exists.",
    CREATE_CUSTOMER_STORE_FAILURE: "Failed to create Customer-store.",
    FETCH_CUSTOMER_STORE_FAILURE: "Failed to fetch Customer-store.",
    MISSING_CUSTOMER_STORE_DETAILS: "Missing Customer-store details.",
    CUSTOMER_STORE_ID_REQUIRED: "Customer-store id required.",
    FETCH_CUSTOMER_STORE_LIST_FAILURE: "Failed to fetch Customer-store list.",
    DELETE_CUSTOMER_STORE_FAILURE: "Failed to delete Customer-store.",
    CUSTOMER_STORE_NOT_EXIST: "Customer-store not exists.",
    CUSTOMER_STORE_UPDATE_FAILURE: "Failed to update Customer-store.",
    MISSING_ROLE_DETAILS: "Missing role details.",
    ROLE_ALREADY_EXIST: "Role  already exists.",
    ROLE_ID_REQUIRED: "Role id required.",
    ROLE_NOT_EXIST: "Role not exists.",
    ROLE_UPDATE_FAILURE: "Failed to update role.",
    ROLE_FAILURE: "Failed to fetch role.",
    FETCH_ROLE_LIST_FAILURE: "Failed to fetch role list.",
    DELETE_ROLE_FAILURE: "Failed to delete role.",
    ROLE_NAME_NOT_FOUND: "Role Name not found.",
    ROLE_NAME_LENGTH: "Please check the Role name length.",
    MISSING_CUSTOMER_DESIGNATION_DETAILS: "Missing customer designation details",
    CUSTOMER_DESIGNATION_ALREADY_EXIST: "customer designation already exists.",
    CUSTOMER_DESIGNATION_ID_REQUIRED: "customer designation id required.",
    CUSTOMER_DESIGNATION_NOT_EXIST: "customer designation not exists.",
    FETCH_CUSTOMER_DESIGNATION_FAILURE: "Failed to fetch customer designation .",
    CREATE_CUSTOMER_DESIGNATION_FAILURE: "Failed to create customer designation .",
    CUSTOMER_DESIGNATION_NAME_NOT_FOUND: "customer designation name not found.",
    CUSTOMER_DESIGNATION_NAME_LENGTH: "Please check the customer designation name length.",
    CUSTOMER_DESIGNATION_CODE_NOT_FOUND: "customer designation code not found.",
    CUSTOMER_DESIGNATION_UPDATE_FAILURE: "Failed to update customer designation",
    FETCH_CUSTOMER_DESIGNATION_LIST_FAILURE: "Failed to fetch customer designation list.",
    DELETE_CUSTOMER_DESIGNATIONFAILURE: "Failed to delete customer designation .",
    MISSING_GAA_DETAILS: "Missing gaa details.",
    GAA_ALREADY_EXIST: "Gaa already exists.",
    GAA_ID_REQUIRED: "Gaa id required.",
    GAA_NOT_EXIST: "Gaa not exists.",
    GAA_UPDATE_FAILURE: "Failed to update gaa.",
    FETCH_GAA_FAILURE: "Failed to fetch gaa.",
    FETCH_GAA_LIST_FAILURE: "Failed to fetch gaa list.",
    DELETE_GAA_FAILURE: "Failed to delete gaa.",
    GAA_NAME_NOT_FOUND: "Gaa Name not found.",
    GAA_NAME_LENGTH: "Please check the Gaa name length.",
    CREATE_GAA_FAILURE: "Failed to create gaa.",
    MISSING_NETWORK_HIERARCHY_DETAILS: "Missing network hierarchy details.",
    NETWORK_HIERARCHY_ALREADY_EXIST: "Network hierarchy already exists.",
    FETCH_NETWORK_HIERARCHY_FAILURE: "Failed to fetch network hierarchy.",
    CREATE_NETWORK_HIERARCHY_FAILURE: "Failed to create network hierarchy.",
    NETWORK_HIERARCHY_NAME_NOT_FOUND: "Network hierarchy Name not found.",
    NETWORK_HIERARCHY_NAME_LENGTH: "Please check the Network hierarchy name length.",
    NETWORK_HIERARCHY_ID_REQUIRED: "Network hierarchy id required.",
    NETWORK_HIERARCHY_NOT_EXIST: "Network hierarchy not exists.",
    NETWORK_HIERARCHY_UPDATE_FAILURE: "Failed to update Network hierarchy.",
    FETCH_NETWORK_HIERARCHY_LIST_FAILURE: "Failed to fetch network hierarchy list.",
    DELETE_NETWORK_HIERARCHY_FAILURE: "Failed to delete network hierarchy.",
    USER_NAME_NOT_FOUND: "User name not found.",
    USER_NAME_LENGTH: "Please check the user name length.",
    USER_CODE_NOT_FOUND: "User code not found.",
    EMPLOYEE_TYPE_NUMBER_REQUIRED: "Employee type number required.",
    IMEI_NUMBER_REQUIRED: "Imei number required.",
    PAN_NUMBER_REQUIRED: "Pan number required.",
    AADHAR_NUMBER_REQUIRED: "Aadhar number required.",
    DATE_OF_ONBOARDING_REQUIRED: "Date of onboarding required.",
    MISSING_USER_DETAILS: "Missing user details.",
    USER_ALREADY_EXIST: "User already exists.",
    FETCH_USER_FAILURE: "Failed to fetch user.",
    CREATE_USER_FAILURE: "Failed to create user.",
    USER_ID_REQUIRED: "User id required.",
    USER_NOT_EXIST: "User not exists.",
    USER_UPDATE_FAILURE: "Failed to update user.",
    DELETE_USER_FAILURE: "Failed to delete user.",
    MISSING_STOCK_LEDGER_DETAILS: "Missing stock ledger details.",
    FETCH_TRANSACTION_COUNT_FAILURE: "Failed to fetch transaction count.",
    STOCK_LEDGER_DETAILS_ID_REQUIRED: "Stock ledger details id required.",
    CREATE_STOCK_LEDGER_FAILURE: "Failed to create stock ledger.",
    FETCH_STOCK_LEDGER_DETAILS_FAILURE: "Failed to fetch stock ledger details.",
    FETCH_STOCK_LEDGER_FAILURE: "Failed to fetch stock ledger.",
    FETCH_STOCK_LEDGER_DETAIL_LIST_FAILURE: "Failed to fetch stock ledger detail list.",
    FETCH_STOCK_LEDGER_LIST_FAILURE: "Failed to fetch stock ledger list.",
    TRANSACTION_TYPE_NOT_FOUND: "Transaction type not found.",
    INVALID_DETAILS: "Please fill valid Value",
    MOBILENUMBER_NOT_FOUND: "Mobile number not found.",
    EMAIL_PASSWORD_OR_MOBILENUMBER_NOT_FOUND: "email, password or mobilenumber not found",
    TOKEN_NOT_FOUND: "Token Not found!",
    LOGIN_SUCCESS: "Login successfully.",
    PASSWORD_CHANGED: "Password changed successfully.",
    PASSWORD_NOT_CHANGED: "Failed to change password.",
    FETCH_SUPPLIER_REPAIR_CENTER_LIST_FAILURE: "Failed to fetch Supplier-repair-centers list.",
    MISSING_PROJECT_MASTER_MAKER_DETAILS: "Missing project master maker details.",
    MASTER_PROJECT_MAKER_ALREADY_EXIST: "Project master maker already exists.",
    FETCH_PROJECT_MASTER_MAKER_FAILURE: "Failed to fetch project master maker.",
    CREATE_PROJECT_MASTER_MAKER_FAILURE: "Failed to create project master maker.",
    PROJECT_MASTER_MAKER_ID_REQUIRED: "Project master maker id required.",
    PROJECT_MASTER_MAKER_NOT_EXIST: "Project master maker not exists.",
    PROJECT_MASTER_MAKER_UPDATE_FAILURE: "Failed to update project master maker.",
    PROJECT_MASTER_MAKER_NAME_NOT_FOUND: "Project master maker name not found.",
    PROJECT_MASTER_MAKER_NAME_LENGTH: "Please check the project master maker name length.",
    PROJECT_FETCH_MASTER_MAKER_LIST_FAILURE: "Failed to fetch project master maker list.",
    PROJECT_DELETE_MASTER_MAKER_FAILURE: "Failed to delete project master maker.",
    PROJECT_MASTER_MAKER_LOV_LENGTH: "Please check the project master maker lov length.",
    PROJECT_MASTER_MAKER_LOV_NOT_FOUND: "Project Master maker lov not found.",
    PROJECT_MISSING_MASTER_MAKER_LOV_DETAILS: "Missing project master maker lov details.",
    PROJECT_MASTER_MAKER_LOV_ALREADY_EXIST: "Project Master maker lov already exists.",
    PROJECT_MASTER_MAKER_LOV_ID_REQUIRED: "Project Master maker lov id required.",
    PROJECT_MASTER_MAKER_LOV_NOT_EXIST: "Project master maker love not exist",
    PROJECT_FETCH_MASTER_MAKER_LOV_FAILURE: "Failed to fetch project master maker lov.",
    CREATE_PROJECT_MASTER_MAKER_LOV_FAILURE: "Failed to create project master maker lov.",
    PROJECT_MASTER_MAKER_LOV_UPDATE_FAILURE: "Failed to update project master maker lov.",
    FETCH_PROJECT_MASTER_MAKER_LOV_LIST_FAILURE: "Failed to fetch project master maker lov list.",
    DELETE_PROJECT_MASTER_MAKER_LOV_FAILURE: "Failed to delete project master maker lov.",
    SECRET_IS_MISSING: "Secret Key is mising",
    INVALID_SECRET: "Invalid Secret",
    RANGE_EXCEEDED: "Range exceeded.",
    MISSING_TRANSACTION_TYPE_DETAILS: "Missing transaction type details.",
    CONTRACTOR_STORE_CODE_NOT_FOUND: "Contractor store code not found.",
    CUSTOMER_STORE_CODE_NOT_FOUND: "Customer store code not found.",
    FIRM_LOCATION_CODE_NOT_FOUND: "Firm location code not found.",
    FIRM_CODE_NOT_FOUND: "Firm code not found.",
    LOCATION_SITE_STORE_CODE_NOT_FOUND: "Location site store code not found.",
    MATERIAL_CODE_NOT_FOUND: "Material code not found.",
    PROJECT_SITE_STORE_CODE_NOT_FOUND: "Project site store code not found.",
    SUPPLIER_REPAIR_CENTER_CODE_NOT_FOUND: "Supplier repair center code not found.",
    SUPPLIER_CODE_NOT_FOUND: "Supplier code not found.",
    MISSING_REQUIRED_DETAILS: "Missing Required details.",
    LOCATION_ALREADY_EXIST: "Location already exists.",
    LOCATION_ID_REQUIRED: "Location id required.",
    LOCATION_NOT_EXIST: "Location not exists.",
    LOCATION_CODE_NOT_FOUND: "Location code not found.",
    CREATE_LOCATION_FAILURE: "Failed to create location.",
    FETCH_LOCATION_FAILURE: "Failed to fetch locations.",
    LOCATION_UPDATE_FAILURE: "Failed to update location.",
    FETCH_ORGANIZATION_LIST_FAILURE: "Failed to fetch organization list.",
    DELETE_ORGANIZATION_LOCATION_FAILURE: "Failed to delete Location.",
    ORGANIZATION_STORE_NAME_NOT_FOUND: "Organization store name not found.",
    ORGANIZATION_STORE_CODE_NOT_FOUND: "Organization store code not found.",
    MISSING_ORGANIZATION_STORE_DETAILS: "Missing organization store details.",
    ORGANIZATION_STORE_ALREADY_EXIST: "Organization store already exist.",
    ORGANIZATION_STORE_ID_REQUIRED: "Organization store id required.",
    ORGANIZATION_STORE_NOT_EXIST: "Organization store not exist.",
    FETCH_ORGANIZATION_STORE_FAILURE: "Failed to fetch organization store.",
    CREATE_ORGANIZATION_STORE_FAILURE: "Failed to create organization store.",
    ORGANIZATION_STORE_UPDATE_FAILURE: "Failed to update organization store.",
    FETCH_ORGANIZATION_STORE_LIST_FAILURE: "Failed to fetch organization store list.",
    DELETE_ORGANIZATION_STORE_FAILURE: "Failed to delete organization store.",
    ORGANIZATION_STORE_LOCATION_NAME_NOT_FOUND: "Organization store location name not found.",
    ORGANIZATION_STORE_LOCATION_CODE_NOT_FOUND: "Organization store location code not found.",
    MISSING_ORGANIZATION_STORE_LOCATION_DETAILS: "Missing organization store location details.",
    ORGANIZATION_STORE_LOCATION_ALREADY_EXIST: "Organization store location already exist.",
    ORGANIZATION_STORE_LOCATION_ID_REQUIRED: "Organization store location id required.",
    ORGANIZATION_STORE_LOCATION_NOT_EXIST: "Organization store location not exist.",
    FETCH_ORGANIZATION_STORE_LOCATION_FAILURE: "Failed to fetch organization store location.",
    CREATE_ORGANIZATION_STORE_LOCATION_FAILURE: "Failed to create organization store location.",
    ORGANIZATION_STORE_LOCATION_UPDATE_FAILURE: "Failed to update organization store location.",
    FETCH_ORGANIZATION_STORE_LOCATION_LIST_FAILURE: "Failed to fetch organization store location list.",
    DELETE_ORGANIZATION_STORE_LOCATION_FAILURE: "Failed to delete organization store location.",
    MISSING_FORM_DETAILS: "Missing form details.",
    FORM_DATA_SAVED_SUCCESSFULLY: "Form data saved successfully",
    FORM_DATA_UPDATED_SUCCESSFULLY: "Form data updated successfully",
    FORM_ALREADY_EXIST: "Form already exists.",
    FORM_ID_REQUIRED: "Form id required.",
    FORM_ALREADY_PUBLISHED: "Form Already Published.",
    FORM_UPDATED_SUCCESSFULLY: "Form updated successfully.",
    FORM_CREATED_SUCCESSFULLY: "Form created successfully.",
    FORM_PUBLISHED_SUCCESSFULLY: "Form Published Successfully",
    FORM_NAME_ALREADY_EXISTS: "Form with this name already exists.",
    FORM_NOT_EXIST: "Form not exists.",
    FORM_UPDATE_FAILURE: "Failed to update form.",
    FETCH_FORM_LIST_FAILURE: "Failed to fetch form list.",
    DELETE_FORM_FAILURE: "Failed to delete form.",
    FORM_FAILURE: "Failed to fetch form.",
    FORM_NAME_NOT_FOUND: "Form Name not found.",
    FORM_NAME_LENGTH: "Please check the Form name length.",
    CREATE_FORM_FAILURE: "Failed to create form.",
    MISSING_REQUEST_DETAILS: "Missing request details.",
    REQUEST_ID_REQUIRED: "Request id required.",
    CREATE_REQUEST_FAILURE: "Failed to create request.",
    FETCH_REQUEST_FAILURE: "Failed to fetch request.",
    FETCH_REQUEST_LIST_FAILURE: "Failed to fetch request list.",
    MISSING_FORMATTRIBUTES_DETAILS: "Missing form attributes details.",
    FORMATTRIBUTES_ALREADY_EXIST: "Form attributes already exists.",
    FORMATTRIBUTES_ID_REQUIRED: "Form attributes id required.",
    FORMATTRIBUTES_NOT_EXIST: "Form attributes not exists.",
    FORMATTRIBUTES_UPDATE_FAILURE: "Failed to update form attributes.",
    FETCH_FORMATTRIBUTES_LIST_FAILURE: "Failed to fetch form attributes list.",
    DELETE_FORMATTRIBUTES_FAILURE: "Failed to delete form attributes.",
    FORMATTRIBUTES_FAILURE: "Failed to fetch form attributes.",
    FORMATTRIBUTES_NAME_NOT_FOUND: "Form attributes Name not found.",
    FORMATTRIBUTES_NAME_LENGTH: "Please check the Form attributes name length.",
    CREATE_FORMATTRIBUTES_FAILURE: "Failed to create form attributes.",

    // attribute validation block
    ATTRIBUTE_VALIDATION_BLOCK_NAME_NOT_FOUND: "Attribute validation block name not found.",
    ATTRIBUTE_VALIDATION_BLOCK_TYPE_NOT_FOUND: "Attribute validation block type not found.",
    ATTRIBUTE_VALIDATION_BLOCK_MESSAGE_NOT_FOUND: "Attribute validation block message not found.",
    ATTRIBUTE_VALIDATION_BLOCK_NAME_LENGTH: "Please check the attribute validation block name length.",
    ATTRIBUTE_VALIDATION_BLOCK_ID_REQUIRED: "Attribute validation block id is required.",
    MISSING_ATTRIBUTE_VALIDATION_BLOCK: "Missing Attribute validation block details.",
    ATTRIBUTE_VALIDATION_BLOCK_NOT_EXIST: "Attribute validation block not exists.",
    ATTRIBUTE_VALIDATION_BLOCK_ALREADY_EXISTS: "Attribute validation block already exists.",
    FAILED_ATTRIBUTE_VALIDATION_BLOCK_CREATE: "Failed to create Attribute validation block.",
    FAILED_ATTRIBUTE_VALIDATION_BLOCK_UPDATE: "Failed to update Attribute validation block.",
    FAILED_ATTRIBUTE_VALIDATION_BLOCK_DELETE: "Failed to delete Attribute validation block.",
    FAILED_ATTRIBUTE_VALIDATION_BLOCK_FETCH: "Failed to fetch Attribute validation block.",
    ATTRIBUTE_VALIDATION_BLOCK_UPDATED: "Attribute validation block updated successfully.",
    ATTRIBUTE_VALIDATION_BLOCK_CREATED_SUCCESSFULLY: "Attribute Validation Block Created Successfully",

    // attribut visibility block
    ATTRIBUTE_VISIBILITY_BLOCK_NAME_NOT_FOUND: "Attribute visibility block name not found.",
    ATTRIBUTE_VISIBILITY_BLOCK_TYPE_NOT_FOUND: "Attribute visibility block type not found.",
    ATTRIBUTE_VISIBILITY_BLOCK_VISIBLE_COLUMNS_NOT_FOUND: "Attribute visibility block visible columns not found.",
    ATTRIBUTE_VISIBILITY_BLOCK_NAME_LENGTH: "Please check the attribute visibility block name length.",
    ATTRIBUTE_VISIBILITY_BLOCK_ID_REQUIRED: "Attribute visibility block id is required.",
    MISSING_ATTRIBUTE_VISIBILITY_BLOCK: "Missing Attribute visibiliy block details.",
    ATTRIBUTE_VISIBILITY_BLOCK_NOT_EXIST: "Attribute visibiliy block not exists.",
    ATTRIBUTE_VISIBILITY_BLOCK_ALREADY_EXISTS: "Attribute visibiliy block already exists.",
    FAILED_ATTRIBUTE_VISIBILITY_BLOCK_CREATE: "Failed to create Attribute visibiliy block.",
    FAILED_ATTRIBUTE_VISIBILITY_BLOCK_UPDATE: "Failed to update Attribute visibiliy block.",
    FAILED_ATTRIBUTE_VISIBILITY_BLOCK_DELETE: "Failed to delete Attribute visibiliy block.",
    FAILED_ATTRIBUTE_VISIBILITY_BLOCK_FETCH: "Failed to fetch Attribute visibiliy block.",
    ATTRIBUTE_VISIBILITY_BLOCK_UPDATED: "Attribute visibility block updated successfully.",
    ATTRIBUTE_VISIBILITY_BLOCK_CREATED_SUCCESSFULLY: "Attribute Visibility Block Created Successfully",

    // attribute validation conditions

    ATTRIBUTE_VALIDATION_CONDITION_OPERATOR_KEY_NOT_FOUND: "Attribute validation condition operator key not found.",
    ATTRIBUTE_VALIDATION_CONDITION_ID_REQUIRED: "Attribute validation condition id is required.",
    FAILED_ATTRIBUTE_VALIDATION_CONDITION_CREATE: "Failed to create Attribute validation condition.",
    MISSING_ATTRIBUTE_VALIDATION_CONDITION: "Missing Attribute validation condition details.",
    ATTRIBUTE_VALIDATION_CONDITION_ALREADY_EXISTS: "Attribute validation condition already exists.",
    FAILED_ATTRIBUTE_VALIDATION_CONDITION_UPDATE: "Failed to update Attribute validation condition.",
    FAILED_ATTRIBUTE_VALIDATION_CONDITION_DELETE: "Failed to delete Attribute validation condition.",
    FAILED_ATTRIBUTE_VALIDATION_CONDITION_FETCH: "Failed to fetch Attribute validation condition.",

    // attribute visibility conditions

    ATTRIBUTE_VISIBILITY_CONDITION_OPERATOR_KEY_NOT_FOUND: "Attribute visibility condition operator key not found.",
    MISSING_ATTRIBUTE_VISIBILITY_CONDITION: "Missing Attribute visibility condition details.",
    FAILED_ATTRIBUTE_VISIBILITY_CONDITION_CREATE: "Failed to create Attribute visibility condition.",
    ATTRIBUTE_VISIBILITY_CONDITION_ID_REQUIRED: "Attribute visibility condition id is required.",
    ATTRIBUTE_VISIBILITY_CONDITION_ALREADY_EXISTS: "Attribute visibility condition already exists.",
    FAILED_ATTRIBUTE_VISIBILITY_CONDITION_UPDATE: "Failed to update Attribute visibility condition.",
    FAILED_ATTRIBUTE_VISIBILITY_CONDITION_DELETE: "Failed to delete Attribute visibility condition.",
    FAILED_ATTRIBUTE_VISIBILITY_CONDITION_FETCH: "Failed to fetch Attribute visibility condition.",

    // gaaLevelEntries
    MISSING_GAA_LEVEL_ENTRIES_DETAILS: "Missing gaa level entries details.",
    GAA_LEVEL_ENTRIES_ID_REQUIRED: "Gaa level entry id required.",
    GAA_LEVEL_ENTRIES_ALREADY_EXIST: "Gaa level entry already exists.",
    GAA_LEVEL_ENTRIES_NOT_EXIST: "Gaa level entry not exists.",
    FETCH_GAA_LEVEL_ENTRIES_FAILURE: "Failed to fetch gaa level entries.",
    CREATE_GAA_LEVEL_ENTRIES_FAILURE: "Failed to create gaa level entries.",
    FETCH_GAA_LEVEL_ENTRIES_LIST_FAILURE: "Failed to fetch gaa level entries list.",
    GAA_LEVEL_ENTRIES_UPDATE_FAILURE: "Failed to update gaa level entries.",
    DELETE_GAA_LEVEL_ENTRIES_FAILURE: "Failed to delete gaa level entries.",
    GAA_LEVEL_ENTRIES_NAME_NOT_FOUND: "Gaa level entry name not found.",
    GAA_LEVEL_ENTRIES_NAME_LENGTH: "Please check the Gaa level entry name length.",
    GAA_LEVEL_ENTRIES_CODE_NOT_FOUND: "Gaa level entry code not found.",

    // formValidationBlock
    FORMVALIDATIONBLOCK_ALREADY_EXIST: "Form validation block already exists.",
    FORMVALIDATIONBLOCK_ID_REQUIRED: "Form validation block formId required.",
    FORMVALIDATIONBLOCK_NOT_EXIST: "Form validation block not exists.",
    FORMVALIDATIONBLOCK_UPDATE_FAILURE: "Failed to update form validation block.",
    FETCH_FORMVALIDATIONBLOCK_LIST_FAILURE: "Failed to fetch form validation block list.",
    DELETE_FORMVALIDATIONBLOCK_FAILURE: "Failed to delete form validation block.",
    FORMVALIDATIONBLOCK_FAILURE: "Failed to fetch form validation block.",
    MISSING_FORMVALIDATION_BLOCK: "Missing from validation block details.",
    CREATE_FORMVALIDATIONBLOCK_FAILURE: "Failed to create form validation block.",

    // formVisibilityBlock

    FORMVISIBILTIYBLOCK_ALREADY_EXIST: "Form visibility block already exists.",
    FORMVISIBILTIYBLOCK_ID_REQUIRED: "Form visibility block formId required.",
    FORMVISIBILTIYBLOCK_NOT_EXIST: "Form visibility block not exists.",
    FORMVISIBILTIYBLOCK_UPDATE_FAILURE: "Failed to update form visibility block.",
    FETCH_FORMVISIBILTIYBLOCK_LIST_FAILURE: "Failed to fetch form visibility block list.",
    DELETE_FORMVISIBILTIYBLOCK_FAILURE: "Failed to delete form visibility block.",
    FORMVISIBILTIYBLOCK_FAILURE: "Failed to fetch form visibility block.",
    MISSING_FORMVISIBILTIY_BLOCK: "Missing from visibility block details.",
    CREATE_FORMVISIBILTIYBLOCK_FAILURE: "Failed to create form visibility block.",

    // networkLevelEntries

    MISSING_NETWORK_LEVEL_ENTRIES_DETAILS: "Missing network level entries details.",
    NETWORK_LEVEL_ENTRIES_ID_REQUIRED: "Network level entry id required.",
    NETWORK_LEVEL_ENTRIES_ALREADY_EXIST: "Network level entry already exists.",
    NETWORK_LEVEL_ENTRIES_NOT_EXIST: "Network level entry not exists.",
    FETCH_NETWORK_LEVEL_ENTRIES_FAILURE: "Failed to fetch network level entries.",
    CREATE_NETWORK_LEVEL_ENTRIES_FAILURE: "Failed to create network level entries.",
    FETCH_NETWORK_LEVEL_ENTRIES_LIST_FAILURE: "Failed to fetch network level entries list.",
    NETWORK_LEVEL_ENTRIES_UPDATE_FAILURE: "Failed to update network level entries.",
    DELETE_NETWORK_LEVEL_ENTRIES_FAILURE: "Failed to delete network level entries.",
    NETWORK_LEVEL_ENTRIES_NAME_NOT_FOUND: "Network level entry name not found.",
    NETWORK_LEVEL_ENTRIES_NAME_LENGTH: "Please check the Network level entry name length.",
    NETWORK_LEVEL_ENTRIES_CODE_NOT_FOUND: "Network level entry code not found.",
    MPIN_CHANGED: "Mpin changed successfully.",

    // workAreaAssignment

    DATE_FROM_IS_REQUIRED: "Date from is required.",
    WORK_AREA_ASSIGNMENT_ID_REQUIRED: "Work Area Assignment id is required.",
    MISSING_WORK_AREA_ASSIGNMENT_DETAILS: "Missing Work Area Assignment Details.",
    MISSING_WORK_AREA_ASSIGNMENT_ALREADY_EXISTS: "Work Area Assignment already exists.",
    FAILED_WORK_AREA_ASSIGNMENT_CREATE: "Failed to create work area assignment",
    FAILED_WORK_AREA_ASSIGNMENT_UPDATE: "Failed to update work area assignment",
    FAILED_WORK_AREA_ASSIGNMENT_DELETE: "Failed to delete work area assignment",
    FAILED_WORK_AREA_ASSIGNMENT_FETCH: "Failed to fetch work area assignment",
    WORK_AREA_ASSIGNMENT_CREATED_SUCCESSFULLY: "Work area assignment created successfully.",

    // userMasterPermission

    MASTER_ID_IS_REQUIRED: "Master id is required.",
    VIEW_PERMISSION_DETAIL_REQUIRED: "View permission detail is required",
    EDIT_PERMISSION_DETAIL_REQUIRED: "Edit permission detail is required",
    ADD_PERMISSION_DETAIL_REQUIRED: "Add permission detail is required",
    DELETE_PERMISSION_DETAIL_REQUIRED: "Delete permission detail is required",
    MISSING_USER_MASTER_PERMISSION_DETAILS: "User master permission details missing.",
    FAILED_USER_MASTER_PERMISSION_CREATE: "Failed to create user master permission.",
    USER_MASTER_PERMISSION_ID_REQUIRED: "User Master Permission id is required.",
    USER_MASTER_PERMISSION_NOT_EXIST: "User master permission does not exists.",
    FAILED_USER_MASTER_PERMISSION_UPDATE: "Failed to update user master permission.",
    FAILED_USER_MASTER_PERMISSION_DELETE: "Failed to delete user master permission.",
    FAILED_USER_MASTER_PERMISSION_FETCH: "Failed to fetch user master permission.",

    // userMasterColumnPermission
    MISSING_USER_MASTER_COLUMN_PERMISSION_DETAILS: "User master column permission details missing.",
    FAILED_USER_MASTER_COLUMN_PERMISSION_CREATE: "Failed to create user master column permission.",
    USER_MASTER_COLUMN_PERMISSION_ID_REQUIRED: "User Master column Permission id is required.",
    USER_MASTER_COLUMN_PERMISSION_NOT_EXIST: "User master column permission does not exists.",
    FAILED_USER_MASTER_COLUMN_PERMISSION_UPDATE: "Failed to update user master column permission.",
    FAILED_USER_MASTER_COLUMN_PERMISSION_DELETE: "Failed to delete user master column permission.",
    FAILED_USER_MASTER_COLUMN_PERMISSION_FETCH: "Failed to fetch user master column permission.",

    // roleMasterColumnPermission
    FIELD_REQUIRED: "Field is required.",
    FETCH_ROLE_MASTER_COLUMN_PERMISSION_FAILURE: "Failed to fetch role master column permission.",
    CREATE_ROLE_MASTER_COLUMN_PERMISSION_FAILURE: "Failed to create role master column permission.",
    ROLE_MASTER_COLUMN_PERMISSION_UPDATE_FAILURE: "Failed to update role master column permission.",
    DELETE_ROLE_MASTER_COLUMN_PERMISSION_FAILURE: "Failed to delete role master column permission.",
    ROLE_MASTER_COLUMN_PERMISSION_ID_REQUIRED: "Role master column permission id required.",
    MISSING_ROLE_MASTER_COLUMN_PERMISSION_DETAILS: "Missing role master column permission details.",
    ROLE_MASTER_COLUMN_PERMISSION_NOT_EXIST: "Role master column permission not exists.",
    ROLE_MASTER_COLUMN_PERMISSION_ALREADY_EXIST: "Role master column permission already exists.",
    // userMasterLovPermission

    MISSING_USER_MASTER_LOV_PERMISSION_DETAILS: "User master lov permission details missing.",
    FAILED_USER_MASTER_LOV_PERMISSION_CREATE: "Failed to create user master lov permission.",
    USER_MASTER_LOV_PERMISSION_ID_REQUIRED: "User Master lov Permission id is required.",
    USER_MASTER_LOV_PERMISSION_NOT_EXIST: "User master lov permission does not exists.",
    FAILED_USER_MASTER_LOV_PERMISSION_UPDATE: "Failed to update user master lov permission.",
    FAILED_USER_MASTER_LOV_PERMISSION_DELETE: "Failed to delete user master lov permission.",
    FAILED_USER_MASTER_LOV_PERMISSION_FETCH: "Failed to fetch user master lov permission.",

    // MIN (Material Issue Note) Transaction
    MISSING_MIN_TRANSACTION_DETAILS: "Missing MIN transaction details.",
    REQUEST_NUMBER_NOT_FOUND: "Request number not found.",
    FROM_ORGANIZATION_ID_NOT_FOUND: "From organization id not found.",
    FROM_STORE_ID_NOT_FOUND: "From store id not found.",
    FROM_STORE_LOCATION_ID_NOT_FOUND: "From store location id not found.",
    MATERIAL_SERIAL_NUMBER_UPDATE_FAILURE: "Failed to update material serial number status.",
    FETCH_MATERIAL_SERIAL_NUMBER_FAILURE: "Failed to fetch material serial numbers.",

    // roleMasterLovPermission
    FETCH_ROLE_MASTER_LOV_PERMISSION_FAILURE: "Failed to fetch role master lov permission.",
    CREATE_ROLE_MASTER_LOV_PERMISSION_FAILURE: "Failed to create role master lov permission.",
    ROLE_MASTER_LOV_PERMISSION_UPDATE_FAILURE: "Failed to update role master lov permission.",
    DELETE_ROLE_MASTER_LOV_PERMISSION_FAILURE: "Failed to delete role master lov permission.",
    ROLE_MASTER_LOV_PERMISSION_ID_REQUIRED: "Role master lov permission id required.",
    MISSING_ROLE_MASTER_LOV_PERMISSION_DETAILS: "Missing role master lov permission details.",
    ROLE_MASTER_LOV_PERMISSION_NOT_EXIST: "Role master lov permission not exists.",
    ROLE_MASTER_LOV_PERMISSION_ALREADY_EXIST: "Role master lov permission already exists.",

    // CTI Transaction (Contractor To Installer)
    MISSING_CTI_TRANSACTION_DETAILS: "Missing CTI transaction details.",

    // ITI Transaction (Installer To Another Installer)
    MISSING_ITI_TRANSACTION_DETAILS: "Missing ITI transaction details.",
    FROM_INSTALLER_ID_NOT_FOUND: "From installer id not found.",
    TO_INSTALLER_ID_NOT_FOUND: "To installer id not found.",

    // STO Transaction
    MISSING_STO_TRANSACTION_DETAILS: "Missing STO transaction details.",
    MISSING_STO_GRN_TRANSACTION_DETAILS: "Missing STO GRN transaction details.",

    // STC Transaction (Project Site Store to Customer)
    MISSING_STC_TRANSACTION_DETAILS: "Missing STC transaction details.",

    // PTP Transaction (Project to another Project)
    MISSING_PTP_TRANSACTION_DETAILS: "Missing PTP transaction details.",
    FROM_PROJECT_ID_NOT_FOUND: "From project id not found.",

    // SLTSL Transaction (Store Location to Another Store Location)
    MISSING_SLTSL_TRANSACTION_DETAILS: "Missing SLTSL transaction details.",

    // MRR (Material Return Request)
    MISSING_MRR_REQUEST_DETAILS: "Missing MRR request details.",

    // MRN (Material Return Note) Transaction
    MISSING_MRN_TRANSACTION_DETAILS: "Missing MRN transaction details.",

    // Cancel GRN(Goods Receive Note) Transaction
    STORE_ID_REQUIRED: "Store id required.",
    CREATED_AT_REQUIRED: "Created at is required.",
    MISSING_CANCEL_TRANSACTION_DETAILS: "Missing cancel transaction details.",
    TRANSACTION_CAN_NOT_BE_CANCELLED: "Transaction can not be cancelled",

    // Cancel Request
    MISSING_CANCEL_REQUEST_DETAILS: "Missing cancel request details.",
    REQUEST_CAN_NOT_BE_CANCELLED: "Request can not be cancelled.",
    REQUEST_STATUS_UPDATE_FAILURE: "Failed to update request status.",
    REQUEST_ALREADY_CANCELLED: "Request already cancelled.",

    // Approver-Master
    MISSING_APPROVER_DETAILS: "Missing approver details.",
    FETCH_APPROVER_FAILURE: "Failed to fetch approver.",
    APPROVER_ALREADY_EXIST: "Approver already exists.",
    CREATE_APPROVER_FAILURE: "Failed to create approver.",
    APPROVER_ID_REQUIRED: "Approver id required.",
    DELETE_APPROVER_FAILURE: "Failed to delete approver.",
    ORGANIZATION_TYPE_NOT_FOUND: "Organization type not found.",
    ORGANIZATION_NAME_NOT_FOUND: "Organization name not found.",
    EFFECTIVE_FROM_NOT_FOUND: "Effective From not found.",
    APPROVER_UPDATE_FAILURE: "Failed to update Approver.",
    APPROVER_NOT_EXIST: "Approver not exists.",
    // STSRC(Project Site Store to Supplier Repair Center) Transaction
    MISSING_STSRC_TRANSACTION_DETAILS: "Missing STSRC transaction details.",

    // SRCTS(Supplier Repair Center to Project Site Store) Transaction
    MISSING_SRCTS_TRANSACTION_DETAILS: "Missing SRCTS transaction details."
};
